spring.application.name=lms-backend
#local
#server.port=8080
#live
server.port=${PORT:8080}

#local
#spring.data.mongodb.uri=mongodb://localhost:27017/language-learning
#live
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# auto-create indexes for @Indexed
spring.data.mongodb.auto-index-creation=true

app.jwt.secret=__dev_secret_that_is_at_least_32_chars_long__
app.jwt.expiration-ms=3600000
#app.jwt.expiration-ms=60000

spring.security.debug=false
#logging.level.org.springframework.security=DEBUG
