spring.application.name=lms-backend
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/language-learning

# auto-create indexes for @Indexed
spring.data.mongodb.auto-index-creation=true

#app.jwt.secret=mysuperlongsecretkey_that_is_at_least_32_chars_long
#app.jwt.secret=${JWT_SECRET:change-this-long-random-secret-at-least-64-bytes}
app.jwt.secret=__dev_secret_that_is_at_least_32_chars_long__
app.jwt.expiration-ms=3600000
#app.jwt.expiration-ms=60000

spring.security.debug=true
logging.level.org.springframework.security=DEBUG
